services:
  app:
    container_name: homelib
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - homelib-network
    restart: always

  db:
    image: postgres:alpine
    container_name: homelib-db
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgress-db-volume:/var/lib/postgresql/data
    networks:
      - homelib-network
    restart: always


volumes:
  postgress-db-volume:

networks:
  homelib-network:
    driver: bridge